name: Run indexer

on:
  schedule:
  - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Create bash file for cloning
      run: |
        make clonerepos.sh
    - name: Clone repos
      run: make clone
    - name: Run indexer
      run: make index
    - name: Commit files
      continue-on-error: true # No changes = Failure
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Indexer"
        git add index metadata.json
        git commit -m "Index update"
    - name: Push changes
      run: |
        credential="$(echo -n "x-access-token:$GITHUB_TOKEN" | base64 -w0)"
        echo "::add-mask::$credential"
        git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic $credential"
        git push
